### ISSUE TITLE
使用这个后直接点击好像无法输入单词

### ISSUE THREAD

**Issue by ilivid** [nexmoe/saladict-skin#1]
点击右上角应用栏里的icon，弹出的界面里似乎无法输入。

不过颜值不错，赞

**Comment by shuangyu886** [comment]
> 点击右上角应用栏里的icon，弹出的界面里似乎无法输入。
> 
> 不过颜值不错，赞

代码里标注了隐藏搜索框代码，可以删去或注释，然后把搜索框文本改为黑色就可以了。
.menuBar-SearchBox_Wrap,
.menuBar-Btn[title="查单词"]
删掉

在最上面加上：
.menuBar-SearchBox {
        color:#000000;//把文本框内的文字颜色改为#000000
}

![image](https://user-images.githubusercontent.com/93515160/146295679-0d5afd96-ae02-4828-bf5d-20aa037c6a0f.png)
